export const desktopIpcChannels = {
  getStatus: "desktop:get-status",
  listProjects: "catalog:list-projects",
  addProject: "catalog:add-project",
  chooseProjectFolder: "catalog:choose-project-folder",
  chooseProjectScanRoot: "catalog:choose-scan-root",
  scanProjects: "catalog:scan-projects",
  getWebsiteProducts: "website:products",
  previewWebsiteChange: "website:preview-change",
  applyWebsiteChange: "website:apply-change",
  chooseArtifact: "release:choose-artifact",
  choosePatch: "patch:choose",
  previewPatch: "patch:preview",
  importPatch: "patch:import",
  openProjectFolder: "artifacts:open-project-folder",
  createProjectZip: "artifacts:create-zip",
  buildProjectExecutable: "artifacts:build-executable",
  previewRelease: "release:preview",
  publishRelease: "release:publish",
  getActivity: "activity:list",
  getDeploymentReadiness: "deployment:readiness",
  buildWebsite: "website:build",
  getPreviewStatus: "website-preview:status",
  startWebsitePreview: "website-preview:start",
  stopWebsitePreview: "website-preview:stop",
  scanTheme: "theme:scan",
  syncTheme: "theme:sync",
  chooseMediaFiles: "media:choose-files",
  scanMediaInbox: "media:scan-inbox",
  listPendingMediaUploads: "media:list-pending",
  startMediaUpload: "media:start-upload",
  retryMediaFinalize: "media:retry-finalize",
  mediaProgress: "media:progress",
  getDevicePairingStatus: "media:pairing-status",
  pairDevice: "media:pair",
  unpairDevice: "media:unpair",
  openMediaShareUrl: "media:open-share-url",
} as const;

export type DesktopIpcChannel = (typeof desktopIpcChannels)[keyof typeof desktopIpcChannels];
