export const desktopIpcChannels = {
  getStatus: "desktop:get-status",
  listProjects: "catalog:list-projects",
  addProject: "catalog:add-project",
  chooseProjectFolder: "catalog:choose-project-folder",
  chooseProjectScanRoot: "catalog:choose-scan-root",
  scanProjects: "catalog:scan-projects",
  getWebsiteProducts: "website:products",
  previewWebsiteChange: "website:preview-change",
  applyWebsiteChange: "website:apply-change",
  chooseArtifact: "release:choose-artifact",
  choosePatch: "patch:choose",
  previewPatch: "patch:preview",
  importPatch: "patch:import",
  previewRelease: "release:preview",
  publishRelease: "release:publish",
  getActivity: "activity:list",
  getDeploymentReadiness: "deployment:readiness",
  buildWebsite: "website:build",
  getPreviewStatus: "website-preview:status",
  startWebsitePreview: "website-preview:start",
  stopWebsitePreview: "website-preview:stop",
  scanTheme: "theme:scan",
  syncTheme: "theme:sync",
} as const;

export type DesktopIpcChannel = (typeof desktopIpcChannels)[keyof typeof desktopIpcChannels];
