import { ChildProcess, spawn } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { access, copyFile, mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import type { ActivityEntry, DeploymentReadiness, OperationResult, PreviewStatus, ReleaseDraft, ThemeFileState, ThemeScan } from "../src/shared/desktop";
import type { CatalogProject } from "../src/shared/desktop";

const themeFiles = [
  ["src/kcxThemeTypes.ts", "src/renderer/theme/kcxThemeTypes.ts"],
  ["src/kcxPalette.ts", "src/renderer/theme/kcxPalette.ts"],
  ["styles/kcx-theme.css", "src/renderer/styles/kcx-theme.css"],
  ["styles/kcx-glow-utils.css", "src/renderer/styles/kcx-glow-utils.css"],
] as const;

const isInside = (base: string, candidate: string) => { const rel = relative(base, candidate); return rel && !rel.startsWith("..") && !resolve(candidate).includes("..") || resolve(base) === resolve(candidate); };
const digest = async (file: string) => createHash("sha256").update(await readFile(file)).digest("hex");

export class PlatformService {
  private preview: ChildProcess | null = null;
  private previewStatus: PreviewStatus = { running: false, url: null, stdout: [], stderr: [] };
  private readonly activityFile: string;
  constructor(private readonly appRoot: string, private readonly userData: string) { this.activityFile = join(userData, "activity.json"); }

  async getActivity(): Promise<ActivityEntry[]> { try { return JSON.parse(await readFile(this.activityFile, "utf8")) as ActivityEntry[]; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } }
  async record(action: string, detail: string, level: ActivityEntry["level"] = "info"): Promise<void> { const next = [{ id: randomUUID(), at: new Date().toISOString(), level, action, detail }, ...(await this.getActivity())].slice(0, 250); await this.atomicJson(this.activityFile, next); }
  async buildWebsite(): Promise<OperationResult> { const result = await this.run("npm.cmd", ["run", "build"], this.appRoot); await this.record("Website build", result.ok ? "Website build succeeded" : "Website build failed", result.ok ? "info" : "error"); return result; }
  async deploymentReadiness(): Promise<DeploymentReadiness> { const git = await this.run("git", ["status", "--short", "--branch"], this.appRoot); const vercel = await this.run("vercel", ["--version"], this.appRoot); return { branch: git.output?.split(/\r?\n/)[0] || "unavailable", gitStatus: (git.output || "").split(/\r?\n/).slice(1).filter(Boolean), websiteBuildReady: (await this.run("npm.cmd", ["run", "build"], this.appRoot)).ok, vercelCliAvailable: vercel.ok, deployAllowed: false }; }
  getPreviewStatus(): PreviewStatus { return { ...this.previewStatus, stdout: [...this.previewStatus.stdout], stderr: [...this.previewStatus.stderr] }; }
  async startPreview(): Promise<PreviewStatus> { if (this.preview) return this.getPreviewStatus(); const port = 5180 + Math.floor(Math.random() * 200); const child = spawn(process.execPath, [join(this.appRoot, "node_modules", "vite", "bin", "vite.js"), "--host", "127.0.0.1", "--port", String(port), "--strictPort"], { cwd: this.appRoot }); this.preview = child; this.previewStatus = { running: true, url: `http://127.0.0.1:${port}`, stdout: [], stderr: [] }; child.stdout?.on("data", (chunk) => { this.previewStatus.stdout = [...this.previewStatus.stdout, String(chunk).trim()].slice(-100); }); child.stderr?.on("data", (chunk) => { this.previewStatus.stderr = [...this.previewStatus.stderr, String(chunk).trim()].slice(-100); }); child.on("exit", () => { this.preview = null; this.previewStatus.running = false; }); await this.record("Website preview", `Started ${this.previewStatus.url}`); return this.getPreviewStatus(); }
  async stopPreview(): Promise<PreviewStatus> { this.preview?.kill(); this.preview = null; this.previewStatus.running = false; await this.record("Website preview", "Stopped"); return this.getPreviewStatus(); }
  async publishRelease(draft: ReleaseDraft, project: CatalogProject | undefined): Promise<OperationResult> { if (!project) return { ok: false, message: "Select a registered project." }; const artifact = resolve(draft.artifactPath); try { const info = await stat(artifact); if (!info.isFile()) return { ok: false, message: "Artifact is not a file." }; const releaseRoot = join(this.appRoot, "public", "downloads", "releases", project.slug); const destination = join(releaseRoot, artifact.split(/[\\/]/).pop()!); if (!isInside(releaseRoot, destination)) return { ok: false, message: "Invalid artifact destination." }; await mkdir(releaseRoot, { recursive: true }); try { await access(destination, constants.R_OK); const backup = join(this.userData, "release-backups", new Date().toISOString().replace(/[:.]/g, "-"), project.slug, artifact.split(/[\\/]/).pop()!); await mkdir(dirname(backup), { recursive: true }); await copyFile(destination, backup); } catch { /* New artifact. */ } await copyFile(artifact, destination); const metadataPath = join(this.appRoot, "src", "data", "publishing-catalog.json"); const metadata = JSON.parse(await readFile(metadataPath, "utf8")) as { releases: unknown[] }; metadata.releases.push({ projectSlug: project.slug, version: draft.version, title: draft.title, channel: draft.channel, file: `downloads/releases/${project.slug}/${artifact.split(/[\\/]/).pop()}`, bytes: info.size, sha256: await digest(artifact), publishedAt: new Date().toISOString() }); await this.atomicJson(metadataPath, metadata); await this.record("Release created", `${project.name} ${draft.version}`); return { ok: true, message: "Release copied with backup and website metadata updated. Deployment remains manual." }; } catch (error) { await this.record("Release publish", String(error), "error"); return { ok: false, message: String(error) }; } }
  async scanTheme(project: CatalogProject | undefined): Promise<ThemeScan> { if (!project) throw new Error("Select a registered project."); const sourceRoot = join(this.appRoot, "theme-engine"); const files: ThemeFileState[] = await Promise.all(themeFiles.map(async ([source, destination]) => { const sourcePath = join(sourceRoot, source); const destinationPath = resolve(project.folder, destination); if (!isInside(resolve(project.folder), destinationPath)) throw new Error("Theme destination escaped the project folder."); try { await access(destinationPath, constants.R_OK); return { source, destination, status: await digest(sourcePath) === await digest(destinationPath) ? "current" : "outdated" }; } catch { return { source, destination, status: "missing" }; } })); return { projectId: project.id, projectName: project.name, files, ready: files.every((file) => file.status === "current") }; }
  async syncTheme(project: CatalogProject | undefined): Promise<OperationResult> { if (!project) return { ok: false, message: "Select a registered project." }; const scan = await this.scanTheme(project); const sourceRoot = join(this.appRoot, "theme-engine"); const backupRoot = join(project.folder, ".kcx-theme-backups", new Date().toISOString().replace(/[:.]/g, "-")); try { for (const [source, destination] of themeFiles) { const from = join(sourceRoot, source); const to = resolve(project.folder, destination); if (!isInside(resolve(project.folder), to)) throw new Error("Theme destination escaped the project folder."); try { await access(to, constants.R_OK); const backup = join(backupRoot, destination); await mkdir(dirname(backup), { recursive: true }); await copyFile(to, backup); } catch { /* New files do not need backups. */ } await mkdir(dirname(to), { recursive: true }); await copyFile(from, to); } await this.record("Theme sync", `${project.name}: ${scan.files.length} files synchronized`); return { ok: true, message: `Synchronized ${scan.files.length} theme files. Backup: ${backupRoot}` }; } catch (error) { await this.record("Theme sync", `${project.name}: ${String(error)}`, "error"); return { ok: false, message: String(error) }; } }
  private async atomicJson(path: string, value: unknown): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temp = `${path}.${randomUUID()}.tmp`; await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, "utf8"); await rename(temp, path); }
  private run(command: string, args: string[], cwd: string): Promise<OperationResult> { return new Promise((resolveResult) => { const child = spawn(command, args, { cwd, shell: process.platform === "win32", windowsHide: true }); let output = ""; child.stdout?.on("data", (chunk) => output += String(chunk)); child.stderr?.on("data", (chunk) => output += String(chunk)); child.on("error", (error) => resolveResult({ ok: false, message: error.message, output })); child.on("exit", (code) => resolveResult({ ok: code === 0, message: code === 0 ? "Completed" : `Failed with exit code ${code}`, output })); }); }
}
