import { safeStorage } from "electron";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { releaseStorageFingerprint } from "./release-fingerprint";

export type ReleaseStorageSettings = { endpoint: string; bucket: string; region: string; publicBaseUrl: string; hasAccessKey: boolean; hasSecretKey: boolean; configured: boolean; providerCertified: boolean; configurationFingerprint?: string; certificationState: "NOT_CERTIFIED" | "CERTIFIED" | "STALE"; lastConnectionTestAt?: string; lastConnectionTestSucceeded?: boolean; lastProbeAt?: string; lastProbeSucceeded?: boolean; lastPublicDownloadResult?: "PASS" | "FAIL" | "NOT_CONFIGURED" };
type Stored = { endpoint?: string; bucket?: string; region?: string; publicBaseUrl?: string; accessKey?: string; secretKey?: string; certification?: { configurationFingerprint?: string; providerCertified: boolean; lastConnectionTestAt?: string; lastConnectionTestSucceeded?: boolean; lastProbeAt?: string; lastProbeSucceeded?: boolean } };
export class ReleaseStorageSettingsService {
  private readonly path: string;
  constructor(userData: string) { this.path = join(userData, "release-storage-settings.json"); }
  private async read(): Promise<Stored> { try { return JSON.parse(await readFile(this.path, "utf8")) as Stored; } catch { return {}; } }
  private decrypt(value?: string): string { if (!value) return ""; try { return safeStorage.decryptString(Buffer.from(value, "base64")); } catch { return ""; } }
  async get(): Promise<ReleaseStorageSettings> { const s = await this.read(); const access = this.decrypt(s.accessKey); const secret = this.decrypt(s.secretKey); const configured = Boolean(s.endpoint && s.bucket && access && secret); const fingerprint = configured ? releaseStorageFingerprint({ endpoint: s.endpoint ?? "", bucket: s.bucket ?? "", region: s.region ?? "auto", publicBaseUrl: s.publicBaseUrl ?? "", accessKeyId: access, secretAccessKey: secret }) : undefined; const certified = Boolean(configured && s.certification?.providerCertified && s.certification.configurationFingerprint === fingerprint); return { endpoint: s.endpoint ?? "", bucket: s.bucket ?? "", region: s.region ?? "auto", publicBaseUrl: s.publicBaseUrl ?? "", hasAccessKey: Boolean(access), hasSecretKey: Boolean(secret), configured, providerCertified: certified, configurationFingerprint: s.certification?.configurationFingerprint, certificationState: certified ? "CERTIFIED" : s.certification?.configurationFingerprint ? "STALE" : "NOT_CERTIFIED", lastConnectionTestAt: s.certification?.lastConnectionTestAt, lastConnectionTestSucceeded: s.certification?.lastConnectionTestSucceeded, lastProbeAt: s.certification?.lastProbeAt, lastProbeSucceeded: s.certification?.lastProbeSucceeded, lastPublicDownloadResult: s.certification?.lastProbeSucceeded ? "PASS" : undefined }; }
  async certify(kind: "connection" | "probe"): Promise<void> { const s = await this.read(); const accessKeyId = this.decrypt(s.accessKey); const secretAccessKey = this.decrypt(s.secretKey); const now = new Date().toISOString(); const fingerprint = releaseStorageFingerprint({ endpoint: s.endpoint ?? "", bucket: s.bucket ?? "", region: s.region ?? "auto", accessKeyId, secretAccessKey, publicBaseUrl: s.publicBaseUrl ?? "" }); s.certification = { ...(s.certification ?? {}), configurationFingerprint: fingerprint, providerCertified: kind === "probe", ...(kind === "connection" ? { lastConnectionTestAt: now, lastConnectionTestSucceeded: true } : { lastProbeAt: now, lastProbeSucceeded: true }) }; await mkdir(dirname(this.path), { recursive: true }); await writeFile(this.path, JSON.stringify(s, null, 2) + "\n", "utf8"); }
  async getSecrets(): Promise<{ accessKeyId: string; secretAccessKey: string }> { const s = await this.read(); return { accessKeyId: this.decrypt(s.accessKey), secretAccessKey: this.decrypt(s.secretKey) }; }
  async update(input: { endpoint: string; bucket: string; region: string; publicBaseUrl?: string; accessKeyId?: string; secretAccessKey?: string }): Promise<ReleaseStorageSettings> { let endpoint: URL; try { endpoint = new URL(input.endpoint); if (!/^https?:$/.test(endpoint.protocol)) throw new Error(); } catch { throw new Error("Release storage endpoint must be a valid HTTP(S) URL."); } if (!input.bucket.trim() || !input.region.trim()) throw new Error("Release storage bucket and region are required."); if (input.publicBaseUrl) { try { new URL(input.publicBaseUrl); } catch { throw new Error("Public base URL must be a valid URL."); } } const old = await this.read(); const access = input.accessKeyId?.trim() || this.decrypt(old.accessKey); const secret = input.secretAccessKey?.trim() || this.decrypt(old.secretKey); if (Boolean(access) !== Boolean(secret)) throw new Error("Access key ID and secret access key must be configured together."); if (!safeStorage.isEncryptionAvailable()) throw new Error("OS-backed secure storage is unavailable."); const encrypted = (value: string) => value ? safeStorage.encryptString(value).toString("base64") : undefined; await mkdir(dirname(this.path), { recursive: true }); await writeFile(this.path, JSON.stringify({ endpoint: input.endpoint.trim(), bucket: input.bucket.trim(), region: input.region.trim(), publicBaseUrl: input.publicBaseUrl?.trim() ?? "", accessKey: encrypted(access), secretKey: encrypted(secret) }, null, 2) + "\n", "utf8"); return this.get(); }
}
