import { useEffect, useState, type ReactNode } from "react";
import type { NeonCleanupPreview, NeonStorageAnalysis } from "../shared/desktop";
import "./desktop.css";

const formatMb = (value: number) => value.toFixed(2);
const errorText = (error: unknown) => error instanceof Error ? error.message : "Neon storage request failed.";
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="desktop-card desktop-task-card"><h3>{title}</h3>{children}</section>; }

export function NeonStorage() {
  const [analysis, setAnalysis] = useState<NeonStorageAnalysis | null>(null); const [preview, setPreview] = useState<NeonCleanupPreview | null>(null); const [autoClean, setAutoClean] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const analyze = async () => { setBusy(true); setError(""); try { setAnalysis(await window.kcxDesktop!.getNeonStorageAnalysis()); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const inspect = async () => { setBusy(true); setError(""); try { setPreview(await window.kcxDesktop!.previewNeonStorageCleanup()); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  useEffect(() => { void analyze(); void window.kcxDesktop!.getNeonStorageSettings().then((settings) => setAutoClean(settings.autoClean)).catch((e) => setError(errorText(e))); }, []);
  const status = !analysis ? "Unknown" : analysis.thresholdReached ? "Cleanup threshold reached" : analysis.usedPercent >= 75 ? "Approaching threshold" : "Healthy";
  return <div className="desktop-panel-grid"><Panel title="Cloud database"><p>Monitor <strong>neondb</strong> and run only the predefined protected cleanup policy.</p>{error && <p className="desktop-warning">{error}</p>}<div className="desktop-action-row"><button className="desktop-action" onClick={analyze} disabled={busy}>Analyze storage</button><button className="desktop-action desktop-action-secondary" onClick={inspect} disabled={busy}>Preview safe cleanup</button><button className="desktop-action" disabled={busy || !preview?.canClean} onClick={async () => { setBusy(true); try { const result = await window.kcxDesktop!.runNeonStorageCleanup(); setAnalysis(result.analysis); setPreview(null); if (!result.ok) setError(result.message); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }}>Run safe cleanup</button></div></Panel>{analysis && <><div className="desktop-summary-grid"><Panel title="DATABASE"><strong>{analysis.databaseName}</strong></Panel><Panel title="USAGE"><strong>{formatMb(analysis.totalMb)} MB / {analysis.freeTierLimitMb} MB</strong><progress className="neon-progress" value={Math.min(analysis.usedPercent, 100)} max={100} /><small>{analysis.usedPercent.toFixed(1)}% used</small></Panel><Panel title="REMAINING"><strong>{formatMb(analysis.remainingMb)} MB</strong></Panel><Panel title="THRESHOLD"><strong>{analysis.cleanupThresholdMb} MB</strong><span className="desktop-badge">{status}</span></Panel></div><Panel title="Auto-clean when Neon reaches 400 MB"><label className="neon-toggle"><input type="checkbox" checked={autoClean} onChange={async (event) => { try { setAutoClean((await window.kcxDesktop!.setNeonStorageSettings({ autoClean: event.target.checked })).autoClean); } catch (e) { setError(errorText(e)); } }} /> Auto-clean when Neon reaches 400 MB</label><p>This is local to this desktop and uses only the predefined protected cleanup policy.</p></Panel><Panel title="Largest tables"><div className="neon-table-wrap"><table><thead><tr><th>Table</th><th>Rows</th><th>Table size</th><th>Indexes</th><th>Total</th><th>Protection</th></tr></thead><tbody>{analysis.tables.map((table) => <tr key={`${table.schema}.${table.tableName}`}><td>{table.schema}.{table.tableName}</td><td>{table.approximateRowCount}</td><td>{formatMb(table.tableBytes / 1048576)} MB</td><td>{formatMb(table.indexBytes / 1048576)} MB</td><td>{formatMb(table.totalBytes / 1048576)} MB</td><td>{table.protected ? "PROTECTED" : "Not protected"}</td></tr>)}</tbody></table></div></Panel></>}{preview && <Panel title="Cleanup preview"><p>{preview.explanation}</p>{preview.warnings.map((warning) => <p className="desktop-warning" key={warning}>{warning}</p>)}<p>Estimated reclaim: {formatMb(preview.estimatedReclaimBytes / 1048576)} MB</p></Panel>}</div>;
}
