import { DragEvent, useState } from "react";
import type { CatalogProject, NewCatalogProject, PatchPreview, ReleasePreview } from "../shared/desktop";

function DropZone({ accept, label, onPath }: { accept: string; label: string; onPath: (path: string) => void }) {
  const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); const file = event.dataTransfer.files.item(0); if (file) onPath(window.kcxDesktop!.getDroppedPath(file)); };
  return <div className="desktop-card" onDragOver={(event) => event.preventDefault()} onDrop={drop} style={{ padding: "1rem", borderStyle: "dashed" }}><strong>{label}</strong><br /><small>Drag a {accept} here from File Explorer.</small></div>;
}

export function ProjectFolderRegistration({ refresh, setMessage }: { refresh: () => Promise<void>; setMessage: (message: string) => void }) {
  const [folder, setFolder] = useState(""); const [busy, setBusy] = useState(false);
  const register = async () => { if (!folder) return; const name = folder.split(/[\\/]/).filter(Boolean).pop() || "project"; const draft: NewCatalogProject = { name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "project", folder, description: "Registered from folder selection", category: "Uncategorized", currentVersion: "Unreleased", releaseChannel: "stable", websiteVisible: true, downloadVisible: true }; setBusy(true); try { await window.kcxDesktop!.addProject(draft); await refresh(); setMessage("Project folder registered"); } catch (error) { setMessage(error instanceof Error ? error.message : "Project registration failed"); } finally { setBusy(false); } };
  return <section className="desktop-card" style={{ padding: "1rem", marginBottom: "1rem" }}><h2>Quick project registration</h2><p>Browse or drag a project folder, then explicitly register it.</p><button className="desktop-action" disabled={busy} onClick={async () => { const selected = await window.kcxDesktop!.chooseProjectFolder(); if (selected) setFolder(selected); }}>Browse project folder</button><small>{folder || "No folder selected"}</small><DropZone accept="project folder" label="Drop project folder" onPath={setFolder} /><button className="desktop-action" disabled={busy || !folder} onClick={register}>Register selected folder</button></section>;
}

export function ReleaseWizard({ projects, setMessage }: { projects: CatalogProject[]; setMessage: (message: string) => void }) {
  const [step, setStep] = useState(1); const [projectId, setProjectId] = useState(""); const [artifactPath, setArtifactPath] = useState(""); const [version, setVersion] = useState(""); const [title, setTitle] = useState(""); const [preview, setPreview] = useState<ReleasePreview | null>(null);
  const draft = { projectId, artifactPath, version, title, notes: "", channel: "stable" as const };
  const validate = async () => { const result = await window.kcxDesktop!.previewRelease(draft); setPreview(result); setStep(3); setMessage(result.isValid ? "Release preview ready" : "Release validation needs attention"); };
  return <section className="desktop-card" style={{ padding: "1.25rem" }}><p className="desktop-kicker">Release publishing wizard · Step {step} of 3</p>{step === 1 && <><h2>Select project</h2><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Select project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select><button className="desktop-action" disabled={!projectId} onClick={() => setStep(2)}>Continue</button></>}{step === 2 && <><h2>Choose and validate artifact</h2><label>Version<input value={version} placeholder="1.2.3" onChange={(event) => setVersion(event.target.value)} /></label><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><button className="desktop-action" onClick={async () => { const selected = await window.kcxDesktop!.chooseArtifact(); if (selected) setArtifactPath(selected); }}>Browse ZIP / EXE / MSI</button><small>{artifactPath || "No artifact selected"}</small><DropZone accept="ZIP, EXE, or MSI artifact" label="Drop release artifact" onPath={setArtifactPath} /><button className="desktop-action" disabled={!artifactPath || !version || !title} onClick={validate}>Preview before publishing</button><button onClick={() => setStep(1)}>Back</button></>}{step === 3 && <><h2>Review and publish</h2>{preview?.artifact && <p>{preview.artifact.name}<br /><small>{preview.artifact.sha256}</small></p>}{preview?.errors.map((error) => <p className="desktop-error" key={error}>{error}</p>)}{preview?.warnings.map((warning) => <p className="desktop-warning" key={warning}>{warning}</p>)}{preview?.operations.map((operation) => <p key={operation}>{operation}</p>)}<button onClick={() => setStep(2)}>Back to artifact</button><button className="desktop-action" disabled={!preview?.isValid} onClick={async () => { const result = await window.kcxDesktop!.publishRelease(draft); setMessage(result.message); }}>Publish release</button></>}</section>;
}

export function PatchImport({ projects, setMessage }: { projects: CatalogProject[]; setMessage: (message: string) => void }) {
  const [projectId, setProjectId] = useState(""); const [patchPath, setPatchPath] = useState(""); const [preview, setPreview] = useState<PatchPreview | null>(null);
  const check = async () => { const result = await window.kcxDesktop!.previewPatch(projectId, patchPath); setPreview(result); setMessage(result.isValid ? "Patch preview ready" : "Patch preview needs attention"); };
  return <section className="desktop-card" style={{ padding: "1.25rem" }}><p className="desktop-kicker">Separate patch workflow</p><h2>Patch Import</h2><p>Patches are archived separately from release artifacts and are never published as releases.</p><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Select project</option>{projects.map((project) => <option value={project.id} key={project.id}>{project.name}</option>)}</select><button className="desktop-action" onClick={async () => { const selected = await window.kcxDesktop!.choosePatch(); if (selected) setPatchPath(selected); }}>Browse .patch / .diff</button><small>{patchPath || "No patch selected"}</small><DropZone accept=".patch or .diff file" label="Drop patch file" onPath={setPatchPath} /><button className="desktop-action" disabled={!projectId || !patchPath} onClick={check}>Preview patch import</button>{preview && <><p>{preview.fileName} · {preview.bytes ?? 0} bytes</p>{preview.errors.map((error) => <p className="desktop-error" key={error}>{error}</p>)}{preview.operations.map((operation) => <p key={operation}>{operation}</p>)}<button className="desktop-action" disabled={!preview.isValid} onClick={async () => { const result = await window.kcxDesktop!.importPatch(projectId, patchPath); setMessage(result.message); }}>Import patch</button></>}</section>;
}
