import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from "react";
import { App as CapacitorApp } from "@capacitor/app";
import { Browser } from "@capacitor/browser";
import { Clipboard } from "@capacitor/clipboard";
import { Preferences } from "@capacitor/preferences";
import { CheckCircle2, CircleAlert, CloudUpload, Copy, ExternalLink, Film, LoaderCircle, LogOut, RefreshCw, Settings, ShieldCheck, Trash2, Upload } from "lucide-react";
import { API_ORIGIN, listMedia, pairDevice, removeMedia, type MediaItem, type Visibility } from "./lib/api";
import { clearCredential, loadCredential, saveCredential, type DeviceCredential } from "./lib/secure";
import { retryFinalize, uploadFile, type PendingFinalize, type UploadPhase } from "./lib/upload";

type Tab = "media" | "upload" | "settings" | "help";
type Notice = { tone: "success" | "error" | "info"; title: string; detail: string } | null;
const pendingKey = "pending-finalizations";

function formatBytes(value: number) { return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1048576).toFixed(1)} MB`; }
function shareUrl(id: string) { return `${API_ORIGIN}/c/${id}`; }
function statusLabel(item: MediaItem) { return item.originalOnline ? "Online" : item.archiveState === "archived" ? "Archived" : item.archiveState; }
async function loadPending(): Promise<PendingFinalize[]> { const { value } = await Preferences.get({ key: pendingKey }); try { return value ? JSON.parse(value) as PendingFinalize[] : []; } catch { return []; } }
async function savePending(items: PendingFinalize[]) { await Preferences.set({ key: pendingKey, value: JSON.stringify(items) }); }

export function App() {
  const [tab, setTab] = useState<Tab>("media");
  const [credential, setCredential] = useState<DeviceCredential | null>(null);
  const [media, setMedia] = useState<MediaItem[]>([]);
  const [loadingMedia, setLoadingMedia] = useState(false);
  const [notice, setNotice] = useState<Notice>(null);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [deviceName, setDeviceName] = useState("My Android phone"); const [pairing, setPairing] = useState(false);
  const [file, setFile] = useState<File | null>(null); const [visibility, setVisibility] = useState<Visibility>("public"); const [uploadPhase, setUploadPhase] = useState<UploadPhase | null>(null); const [uploadProgress, setUploadProgress] = useState(0); const [uploadDetail, setUploadDetail] = useState("");
  const [pending, setPending] = useState<PendingFinalize[]>([]); const [removingId, setRemovingId] = useState<string | null>(null);

  const refreshMedia = useCallback(async (active = credential) => {
    if (!active) { setMedia([]); return; }
    setLoadingMedia(true);
    try { setMedia((await listMedia(active)).items); }
    catch (error) { setNotice({ tone: "error", title: "Could not load online media", detail: error instanceof Error ? error.message : "Check your connection and paired device." }); }
    finally { setLoadingMedia(false); }
  }, [credential]);

  useEffect(() => { void (async () => { const [stored, recovery] = await Promise.all([loadCredential(), loadPending()]); setCredential(stored); setPending(recovery); if (stored) await refreshMedia(stored); })(); }, [refreshMedia]);
  useEffect(() => { const listener = CapacitorApp.addListener("appStateChange", ({ isActive }) => { if (isActive) void refreshMedia(); }); return () => { void listener.then((handle) => handle.remove()); }; }, [refreshMedia]);

  const pair = async (event: FormEvent) => { event.preventDefault(); setPairing(true); try { const result = await pairDevice(email, password, deviceName); const next = { ...result, deviceName }; await saveCredential(next); setCredential(next); setPassword(""); setNotice({ tone: "success", title: "Device paired", detail: "This phone can now manage KCx Labs Media. Your password was not stored." }); await refreshMedia(next); } catch (error) { setNotice({ tone: "error", title: "Pairing failed", detail: error instanceof Error ? error.message : "Check your owner email and password." }); } finally { setPairing(false); } };
  const unpair = async () => { await clearCredential(); setCredential(null); setMedia([]); setNotice({ tone: "info", title: "Device unpaired", detail: "The local device credential was removed from this phone." }); };
  const selectFile = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0] ?? null; setFile(selected); setUploadPhase(null); setUploadDetail(selected ? "Ready to upload." : ""); };
  const appendPending = async (item: PendingFinalize) => { const next = [...(await loadPending()).filter((entry) => entry.mediaId !== item.mediaId), item]; await savePending(next); setPending(next); };
  const removePending = async (id: string) => { const next = (await loadPending()).filter((entry) => entry.mediaId !== id); await savePending(next); setPending(next); };
  const upload = async () => { if (!credential || !file) return; setUploadPhase("hashing"); setUploadProgress(0); try { const result = await uploadFile(file, visibility, credential, (phase, progress, detail) => { setUploadPhase(phase); setUploadProgress(progress); if (detail) setUploadDetail(detail); }, appendPending, removePending); setUploadPhase("published"); setFile(null); setNotice({ tone: "success", title: result.duplicate ? "Existing clip reused" : "Clip published", detail: result.duplicate ? `This file already exists. Share link: ${result.shareUrl}` : `Your clip is now available. Share link: ${result.shareUrl}` }); await refreshMedia(); } catch { /* The upload helper has set a user-safe status message. */ } };
  const remove = async (item: MediaItem) => { if (!credential || !window.confirm(`Remove “${item.title || item.originalFilename}” from the KCx Labs website? This does not delete the local video on your phone.`)) return; setRemovingId(item.id); try { await removeMedia(item.id, credential); setMedia((items) => items.filter((entry) => entry.id !== item.id)); setNotice({ tone: "success", title: "Removed from website", detail: `${item.title || item.originalFilename} disappeared from this screen. Checking the server list now.` }); setMedia((await listMedia(credential)).items.filter((entry) => entry.id !== item.id)); } catch (error) { setNotice({ tone: "error", title: "Removal failed", detail: error instanceof Error ? error.message : "The clip remains online. Try again." }); } finally { setRemovingId(null); } };
  const copy = async (url: string) => { await Clipboard.write({ string: url }); setNotice({ tone: "success", title: "Link copied", detail: "The clip link is ready to paste." }); };
  const retry = async (item: PendingFinalize) => { if (!credential) return; try { const result = await retryFinalize(item, credential, removePending); setNotice({ tone: "success", title: "Recovery completed", detail: `${item.filename} is published: ${result.shareUrl}` }); await refreshMedia(); } catch (error) { setNotice({ tone: "error", title: "Recovery still needs attention", detail: error instanceof Error ? error.message : "Try again once the connection is stable." }); } };

  const mediaScreen = !credential ? <Empty title="Pair this phone first" detail="Open Settings, sign in with the owner account, then return here to manage online media." action={() => setTab("settings")} actionLabel="Open Settings" /> : loadingMedia && !media.length ? <Empty title="Loading online media" detail="Checking the server for your clips." /> : !media.length ? <Empty title="No online media yet" detail="Upload a video from the Upload tab." action={() => setTab("upload")} actionLabel="Upload a clip" /> : <div className="media-grid">{media.map((item) => <article className="media-card" key={item.id}><div><h3>{item.title || item.originalFilename}</h3>{item.title && item.title !== item.originalFilename && <small>{item.originalFilename}</small>}<div className="chips"><span>{item.visibility}</span><span>{item.status}</span><span>{statusLabel(item)}</span></div></div><div className="media-actions"><button className="secondary" onClick={() => void copy(shareUrl(item.publicId))}><Copy size={15} />Copy link</button><button className="secondary" onClick={() => void Browser.open({ url: shareUrl(item.publicId) })}><ExternalLink size={15} />Open</button><button className="danger" disabled={removingId !== null} onClick={() => void remove(item)}>{removingId === item.id ? "Removing…" : <><Trash2 size={15} />Remove from Website</>}</button></div></article>)}</div>;

  return <main className="app-shell">
    <header className="app-header"><div><p>KCX LABS</p><h1>Media Companion</h1></div><span className={`pair-state ${credential ? "paired" : ""}`}><ShieldCheck size={15} />{credential ? `Paired · ${credential.deviceName}` : "Not paired"}</span></header>
    {notice && <section className={`notice ${notice.tone}`} role="status"><div>{notice.tone === "success" ? <CheckCircle2 size={20} /> : <CircleAlert size={20} />}</div><div><strong>{notice.title}</strong><p>{notice.detail}</p></div><button onClick={() => setNotice(null)} aria-label="Dismiss message">×</button></section>}
    <nav className="tabs" aria-label="Media companion navigation"><button className={tab === "media" ? "active" : ""} onClick={() => setTab("media")}><Film size={18} />Media</button><button className={tab === "upload" ? "active" : ""} onClick={() => setTab("upload")}><Upload size={18} />Upload</button><button className={tab === "settings" ? "active" : ""} onClick={() => setTab("settings")}><Settings size={18} />Settings</button><button className={tab === "help" ? "active" : ""} onClick={() => setTab("help")}>?</button></nav>
    {tab === "media" && <section className="screen"><div className="screen-heading"><div><p className="eyebrow">Online Media</p><h2>Clips on KCx Labs</h2><p>View what is currently stored for your paired account. Returning to the app refreshes this list.</p></div><button className="secondary" onClick={() => void refreshMedia()} disabled={!credential || loadingMedia}>{loadingMedia ? <LoaderCircle className="spin" size={16} /> : <RefreshCw size={16} />}Reload</button></div>{mediaScreen}</section>}
    {tab === "upload" && <section className="screen"><div className="screen-heading"><div><p className="eyebrow">Upload clip</p><h2>Publish a video from this phone</h2><p>Select a video with Android’s system picker, choose its visibility, then publish it through the existing KCx Labs media flow.</p></div></div>{!credential ? <Empty title="Pair before uploading" detail="A paired device is required for secure upload authorization." action={() => setTab("settings")} actionLabel="Pair this phone" /> : <><div className="upload-grid"><section className="panel"><h3>1. Choose a video</h3><label className="file-picker"><input type="file" accept="video/*" onChange={selectFile} />Choose video from device</label><p className="selection">{file ? `${file.name} · ${formatBytes(file.size)}` : "No video selected"}</p><h3>2. Choose visibility</h3><div className="visibility">{(["private", "unlisted", "public"] as Visibility[]).map((value) => <button key={value} className={visibility === value ? "selected" : ""} onClick={() => setVisibility(value)}>{value}<small>{value === "private" ? "Owner only" : value === "unlisted" ? "Anyone with link" : "Listed in Clips"}</small></button>)}</div><button className="primary" disabled={!file || ["hashing", "checking", "authorizing", "uploading", "finalizing"].includes(uploadPhase ?? "")} onClick={() => void upload()}><CloudUpload size={17} />Upload clip</button></section><section className="panel upload-status"><p className="eyebrow">Upload status</p><h3>{uploadPhase ? uploadPhase === "published" ? "Published" : uploadPhase[0].toUpperCase() + uploadPhase.slice(1) : "Ready when you are"}</h3><p>{uploadDetail || "Your file stays on this phone until you choose Upload clip."}</p>{uploadPhase === "uploading" && <><div className="progress"><span style={{ width: `${uploadProgress}%` }} /></div><strong>{uploadProgress}% uploaded</strong></>}{uploadPhase === "failed" && <p className="error">{uploadDetail}</p>}</section></div>{pending.length > 0 && <section className="panel recovery"><p className="eyebrow">Recovery needed</p><h3>Finalize interrupted uploads</h3><p>These uploads reached storage but need one more verification step.</p><div className="recovery-grid">{pending.map((item) => <article key={item.mediaId}><strong>{item.filename}</strong><small>Saved {new Date(item.createdAt).toLocaleString()}</small><button className="secondary" onClick={() => void retry(item)}>Retry finalization</button></article>)}</div></section>}</>}</section>}
    {tab === "settings" && <section className="screen"><div className="screen-heading"><div><p className="eyebrow">Device settings</p><h2>{credential ? "This phone is paired" : "Pair this phone"}</h2><p>{credential ? `Paired as ${credential.deviceName}. The device credential is stored with Android secure storage; your owner password is not stored.` : "Enter the owner account only to create a device credential. Your password is never saved."}</p></div></div>{credential ? <section className="panel settings-card"><ShieldCheck size={28} /><h3>{credential.deviceName}</h3><p>Credential expires {new Date(credential.expiresAt).toLocaleString()}.</p><button className="danger" onClick={() => void unpair()}><LogOut size={16} />Unpair this phone</button></section> : <form className="panel pairing-form" onSubmit={pair}><label>Owner email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Owner password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label>Device name<input required value={deviceName} maxLength={120} onChange={(event) => setDeviceName(event.target.value)} /></label><button className="primary" disabled={pairing}>{pairing ? "Pairing…" : "Pair this phone"}</button></form>}</section>}
    {tab === "help" && <section className="screen help"><p className="eyebrow">Offline guide</p><h2>Using KCx Labs Media</h2><section><h3>Get started</h3><p>Pair this phone in Settings. Then use Media to view online clips or Upload to publish a selected video. The app requests no contacts, camera, microphone, location, or broad storage permissions.</p></section><section><h3>Upload a clip</h3><ol><li>Open Upload and select a video with Android’s system picker.</li><li>Choose private, unlisted, or public visibility.</li><li>Select Upload clip. The app hashes the file, checks duplicates, obtains a short-lived upload authorization, uploads directly to storage, and finalizes publication.</li></ol><p>If a connection drops after storage upload, use the recovery card to retry finalization.</p></section><section><h3>Online media and removal</h3><p>Reload fetches the latest server list, and the app refreshes when you return to it. Remove from Website asks for confirmation, removes the item immediately after server success, then reconciles with the server. This never deletes the original phone file.</p></section><section><h3>Common issues</h3><p>Pairing failures usually mean invalid owner credentials or no network. Expired credentials require pairing again. Upload failures show the current stage; keep the app open during transfer and retry after checking the message.</p></section></section>}
  </main>;
}

function Empty({ title, detail, action, actionLabel }: { title: string; detail: string; action?: () => void; actionLabel?: string }) { return <section className="empty"><Film size={28} /><h3>{title}</h3><p>{detail}</p>{action && <button className="primary" onClick={action}>{actionLabel}</button>}</section>; }
